name: farmers_network_screens
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.4
  badges: ^2.0.3
  custom_navigator: ^0.3.0-nullsafety
  fl_chart: ^0.55.2
  csc_picker: ^0.2.6
  intl: ^0.17.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  hexcolor: ^3.0.1
  grouped_list: ^5.1.2
  table_calendar: ^3.0.8
  comment_tree: ^0.3.0
  syncfusion_flutter_charts: ^20.4.42

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/login.png
      - assets/images/landing.jpg
      - assets/images/farmer.jpeg
      - assets/images/developmentPartners.png
      - assets/images/offtake.png
      - assets/images/trade.png
      - assets/images/calendar-2023-year-december-month-neomorphism-style-planner-template-vector-illustration-eps.jpg_s=1024x1024&w=is&k=20&c=ospIRZwAnqXQFPYALLNeBCbD60gbD9I0OYl6Z_0IMFk=.jpg
      - assets/images/debt - Copy.png
      - assets/images/developmentPartners.png
      - assets/images/farmer.jpeg
      - assets/images/weatherbackground.jpg
      - assets/images/Img/iStock-1442696346.jpg
      - assets/images/iStock-1223021697.jpg
      - assets/images/iStock-1150928206.jpg
      - assets/images/field-and-tractor.png
      - assets/images/futures.png
      - assets/images/offtake.png
      - assets/images/service.png
      - assets/images/Stimulator.png
      - assets/images/Dallan_farm.jpg
      - assets/images/Img/1.jpg
      - assets/images/Img/2.jpg
      - assets/images/Img/4..jpg
      - assets/images/Img/5.png
      - assets/images/Img/6.jpg
      - assets/images/Img/7.jpg
      - assets/images/Img/8.jpg
      - assets/images/Img/9.jpg
      - assets/images/Img/10.png
      - assets/images/Img/11.png
      - assets/newImg/GDDF.png
      - assets/newImg/Nyanza.png
      - assets/newImg/Forum.png
      - assets/newImg/agribusiness.png
      - assets/newImg/consultancy.png
      - assets/newImg/Excellence.png
      - assets/newImg/cocoa.png
      - assets/newImg/Network.png
      - assets/newImg/hustle.png
      - assets/newImg/porridge.png
      - assets/newImg/pineApple.png
      - assets/newImg/Page-20-Image-69.png
      - assets/newImg/orange.png
      - assets/newImg/mangoes.png
      - assets/newImg/pears.png
      - assets/newImg/grappes.png
      - assets/newImg/aggronomy-service.png
      - assets/newImg/Agronomist.png
      - assets/newImg/veterinary.png
      - assets/newImg/seedMerchant.png
      - assets/newImg/soilCare.png
      - assets/newImg/tractor.png
      - assets/newImg/irrigate.png
      - assets/newImg/green.png
      - assets/newImg/spraying.png
      - assets/newImg/dealer.png
      - assets/newImg/coldLogistics.png
      - assets/newImg/packaging.png
      - assets/newImg/agg.png
      - assets/newImg/pen.png
      - assets/newImg/horticulture.png
      - assets/newImg/porridge.png
      - assets/newImg/Page-10-Image-24.png
      - assets/newImg/vegetable-farming.png
      - assets/newImg/Page-10-Image-26.png
      - assets/newImg/Page-10-Image-27.png
      - assets/newImg/Page-10-Image-22.png
      - assets/newImg/Page-10-Image-24.png
      - assets/newImg/TikTok.png
      - assets/newImg/LinkedIn.png
      - assets/newImg/Instagram.png
      - assets/newImg/facebook.png
      - assets/newImg/Whatsapp.png
      - assets/newImg/Youtube.png
      - assets/newImg/strawberries.png
      - assets/newImg/Potatoes.png
      - assets/newImg/avocado.png
      - assets/newImg/catfish.png
      - assets/newImg/indigenousVeggies.png
      - assets/newImg/training.png
      - assets/newImg/tourism.png
      - assets/newImg/sheep.png
      - assets/newImg/cloud-gff6c8cb92_1280.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
